import { createSignal } from "solid-js"

export type SupportedLanguage = "es" | "en"
export type LanguagePreference = "auto" | SupportedLanguage

const messages = {
  es: {
    "cli.usage": "Uso: oec [OPCIONES] [PROYECTO]",
    "cli.help": "Uso: oec [OPCIONES] [PROYECTO]\n\n  -h, --help       Mostrar esta ayuda\n  -V, --version    Mostrar versión\n\nConsulte man oec o docs/manual.md para la referencia completa.",
    "config.invalidJson": "El archivo no contiene JSON válido.",
    "config.invalid": "La configuración no es compatible.",
    "config.keys": "La configuración tiene claves desconocidas o faltantes.",
    "config.version": "La versión del esquema no es compatible.",
    "config.appearance": "La apariencia no es compatible.",
    "config.layout": "El layout no es válido.",
    "config.layoutRange": "El layout contiene valores fuera de rango.",
    "config.editor": "La configuración del editor no es válida.",
    "config.search": "La configuración de búsqueda no es válida.",
    "config.git": "La configuración de Git no es válida.",
    "config.updates": "La configuración de actualizaciones no es válida.",
    "config.tooLarge": "El archivo supera el límite de 256 KB.",
    "config.restored": "CONFIGURACIÓN RESTAURADA",
    "app.explorer": "EXPLORADOR",
    "app.changes": "CAMBIOS",
    "app.previous": "ANTERIOR",
    "app.new": "NUEVO",
    "app.line": "Ln",
    "app.searchFile": "Buscar archivo...",
    "app.results": "{count} resultados",
    "app.findFile": "BUSCAR EN ARCHIVO",
    "app.typeToSearch": "Escribe para buscar...",
    "app.typeTextToSearch": "Escribe un texto para buscar.",
    "app.noMatches": "Sin coincidencias.",
    "app.findHelp": "Flechas resultado | Enter ir | Esc cerrar",
    "app.gitHelp": "+ preparar | - quitar o descartar",
    "overlay.palette": "COMANDOS Y CONFIGURACIÓN",
    "overlay.projectSearch": "BUSCAR EN TODO EL PROYECTO",
    "overlay.exclusions": "EXCLUSIONES DE BÚSQUEDA",
    "overlay.newFile": "NUEVO ARCHIVO",
    "overlay.folder": "Carpeta: {path}",
    "overlay.fileName": "nombre.ext",
    "overlay.pattern": "Carpeta o patrón...",
    "overlay.searching": "Buscando...",
    "overlay.session": "sesión",
    "overlay.project": "proyecto",
    "overlay.paletteHelp": "Flechas seleccionar | Enter ejecutar | Esc cerrar",
    "overlay.projectHelp": "Enter buscar | Ctrl+E exclusiones | Esc cerrar",
    "overlay.exclusionHelp": "Tab completar | Enter alternar | Supr quitar | Esc volver",
    "overlay.newFileHelp": "Enter crear | Esc cancelar",
    "overlay.confirmTitle": "Hay cambios sin guardar.",
    "overlay.confirmDescription": "Elige qué hacer con los cambios pendientes.",
    "overlay.save": "Guardar",
    "overlay.saveUpdate": "Guardar y actualizar",
    "overlay.updateWithoutSave": "Actualizar sin guardar",
    "overlay.saveQuit": "Guardar y salir",
    "overlay.quitWithoutSave": "Salir sin guardar",
    "overlay.saveClose": "Guardar y cerrar",
    "overlay.closeWithoutSave": "Cerrar sin guardar",
    "overlay.confirmHelp": "Flechas arriba/abajo | Enter confirmar | Esc cancelar",
    "overlay.delete": "Eliminar {kind}",
    "overlay.file": "archivo",
    "overlay.directory": "carpeta",
    "overlay.deleteQuestion": "¿Quieres eliminar {name}?",
    "overlay.deleteDirectory": "También se eliminará todo su contenido.",
    "overlay.irreversible": "Esta acción no se puede deshacer.",
    "overlay.actionHelp": "Enter confirmar | Esc cancelar",
    "overlay.discardGit": "Descartar cambio de Git",
    "overlay.discardGitQuestion": "¿Quieres descartar los cambios de {path}?",
    "welcome.tagline": "Editor de proyectos de código abierto para consola",
    "welcome.openPanels": "ABRIR Y MOVERSE ENTRE PANELES",
    "welcome.toggleExplorer": "MOSTRAR / OCULTAR PANEL IZQUIERDO",
    "welcome.toggleChanges": "MOSTRAR / OCULTAR CAMBIOS",
    "welcome.movePanels": "MOVERSE ENTRE PANELES",
    "welcome.files": "ARCHIVOS",
    "welcome.editing": "EDICIÓN Y BÚSQUEDA",
    "welcome.refresh": "Actualizar panel activo",
    "welcome.newFile": "Nuevo archivo",
    "welcome.delete": "Eliminar selección",
    "welcome.open": "Abrir / expandir",
    "welcome.collapseFolder": "Contraer carpeta",
    "welcome.collapseTree": "Contraer árbol",
    "welcome.palette": "Paleta de comandos",
    "welcome.findFile": "Buscar en archivo",
    "welcome.findProject": "Buscar en proyecto",
    "welcome.save": "Guardar",
    "welcome.closeTab": "Cerrar pestaña",
    "welcome.nextTab": "Siguiente pestaña",
    "welcome.clipboard": "Portapapeles",
    "welcome.undoRedo": "Deshacer / rehacer",
    "command.focusLeft": "Mover foco a la izquierda",
    "command.focusRight": "Mover foco a la derecha",
    "command.toggleExplorer": "Mostrar u ocultar explorador",
    "command.toggleGit": "Mostrar u ocultar control de cambios",
    "command.refreshGit": "Actualizar referencias remotas y cambios de Git",
    "command.refresh": "Actualizar panel activo",
    "command.create": "Crear archivo en carpeta seleccionada",
    "command.searchFile": "Buscar archivo por nombre",
    "command.searchText": "Buscar texto",
    "command.searchProject": "Buscar en todo el proyecto",
    "command.exclusions": "Editar exclusiones de búsqueda",
    "command.config": "Editar configuración de OEC",
    "command.manual": "Abrir manual de OEC",
    "command.save": "Guardar archivo",
    "command.close": "Cerrar archivo",
    "command.nextTab": "Pestaña siguiente",
    "command.copy": "Copiar selección",
    "command.paste": "Pegar portapapeles",
    "command.wrap": "Alternar ajuste de línea",
    "command.undo": "Deshacer último cambio",
    "command.redo": "Rehacer último cambio",
    "command.countLines": "Calcular líneas del proyecto",
    "command.palette": "Paleta",
    "command.update": "Actualización",
  },
  en: {
    "cli.usage": "Usage: oec [OPTIONS] [PROJECT]",
    "cli.help": "Usage: oec [OPTIONS] [PROJECT]\n\n  -h, --help       Show this help\n  -V, --version    Show version\n\nSee man oec or docs/manual.md for the full reference.",
    "config.invalidJson": "The file does not contain valid JSON.",
    "config.invalid": "The configuration is not compatible.",
    "config.keys": "The configuration has unknown or missing keys.",
    "config.version": "The schema version is not compatible.",
    "config.appearance": "The appearance configuration is not compatible.",
    "config.layout": "The layout is invalid.",
    "config.layoutRange": "The layout contains out-of-range values.",
    "config.editor": "The editor configuration is invalid.",
    "config.search": "The search configuration is invalid.",
    "config.git": "The Git configuration is invalid.",
    "config.updates": "The update configuration is invalid.",
    "config.tooLarge": "The file exceeds the 256 KB limit.",
    "config.restored": "CONFIGURATION RESTORED",
    "app.explorer": "EXPLORER",
    "app.changes": "CHANGES",
    "app.previous": "PREVIOUS",
    "app.new": "NEW",
    "app.line": "Ln",
    "app.searchFile": "Search files...",
    "app.results": "{count} results",
    "app.findFile": "FIND IN FILE",
    "app.typeToSearch": "Type to search...",
    "app.typeTextToSearch": "Type text to search.",
    "app.noMatches": "No matches.",
    "app.findHelp": "Arrows select | Enter go | Esc close",
    "app.gitHelp": "+ stage | - unstage or discard",
    "overlay.palette": "COMMANDS AND SETTINGS",
    "overlay.projectSearch": "SEARCH ENTIRE PROJECT",
    "overlay.exclusions": "SEARCH EXCLUSIONS",
    "overlay.newFile": "NEW FILE",
    "overlay.folder": "Folder: {path}",
    "overlay.fileName": "name.ext",
    "overlay.pattern": "Folder or pattern...",
    "overlay.searching": "Searching...",
    "overlay.session": "session",
    "overlay.project": "project",
    "overlay.paletteHelp": "Arrows select | Enter run | Esc close",
    "overlay.projectHelp": "Enter search | Ctrl+E exclusions | Esc close",
    "overlay.exclusionHelp": "Tab complete | Enter toggle | Del remove | Esc back",
    "overlay.newFileHelp": "Enter create | Esc cancel",
    "overlay.confirmTitle": "There are unsaved changes.",
    "overlay.confirmDescription": "Choose what to do with pending changes.",
    "overlay.save": "Save",
    "overlay.saveUpdate": "Save and update",
    "overlay.updateWithoutSave": "Update without saving",
    "overlay.saveQuit": "Save and quit",
    "overlay.quitWithoutSave": "Quit without saving",
    "overlay.saveClose": "Save and close",
    "overlay.closeWithoutSave": "Close without saving",
    "overlay.confirmHelp": "Up/down arrows | Enter confirm | Esc cancel",
    "overlay.delete": "Delete {kind}",
    "overlay.file": "file",
    "overlay.directory": "folder",
    "overlay.deleteQuestion": "Do you want to delete {name}?",
    "overlay.deleteDirectory": "All of its contents will also be deleted.",
    "overlay.irreversible": "This action cannot be undone.",
    "overlay.actionHelp": "Enter confirm | Esc cancel",
    "overlay.discardGit": "Discard Git change",
    "overlay.discardGitQuestion": "Do you want to discard changes in {path}?",
    "welcome.tagline": "An open-source project editor for the terminal",
    "welcome.openPanels": "OPEN AND MOVE BETWEEN PANELS",
    "welcome.toggleExplorer": "SHOW / HIDE LEFT PANEL",
    "welcome.toggleChanges": "SHOW / HIDE CHANGES",
    "welcome.movePanels": "MOVE BETWEEN PANELS",
    "welcome.files": "FILES",
    "welcome.editing": "EDITING AND SEARCH",
    "welcome.refresh": "Refresh active panel",
    "welcome.newFile": "New file",
    "welcome.delete": "Delete selection",
    "welcome.open": "Open / expand",
    "welcome.collapseFolder": "Collapse folder",
    "welcome.collapseTree": "Collapse tree",
    "welcome.palette": "Command palette",
    "welcome.findFile": "Find in file",
    "welcome.findProject": "Find in project",
    "welcome.save": "Save",
    "welcome.closeTab": "Close tab",
    "welcome.nextTab": "Next tab",
    "welcome.clipboard": "Clipboard",
    "welcome.undoRedo": "Undo / redo",
    "command.focusLeft": "Move focus left",
    "command.focusRight": "Move focus right",
    "command.toggleExplorer": "Show or hide explorer",
    "command.toggleGit": "Show or hide source control",
    "command.refreshGit": "Refresh Git remote references and changes",
    "command.refresh": "Refresh active panel",
    "command.create": "Create file in selected folder",
    "command.searchFile": "Search files by name",
    "command.searchText": "Search text",
    "command.searchProject": "Search entire project",
    "command.exclusions": "Edit search exclusions",
    "command.config": "Edit OEC configuration",
    "command.manual": "Open OEC manual",
    "command.save": "Save file",
    "command.close": "Close file",
    "command.nextTab": "Next tab",
    "command.copy": "Copy selection",
    "command.paste": "Paste clipboard",
    "command.wrap": "Toggle line wrap",
    "command.undo": "Undo last change",
    "command.redo": "Redo last change",
    "command.countLines": "Count project lines",
    "command.palette": "Palette",
    "command.update": "Update",
  },
} as const

export type MessageKey = keyof typeof messages.es

export function detectSystemLanguage(locale = Intl.DateTimeFormat().resolvedOptions().locale): SupportedLanguage {
  return locale.toLowerCase().startsWith("es") ? "es" : "en"
}

export function resolveLanguage(preference: LanguagePreference | undefined, systemLocale?: string): SupportedLanguage {
  return preference === "es" || preference === "en" ? preference : detectSystemLanguage(systemLocale)
}

const [language, setLanguage] = createSignal<SupportedLanguage>(detectSystemLanguage())

export { language }

export function configureLanguage(preference: LanguagePreference | undefined, systemLocale?: string) {
  setLanguage(resolveLanguage(preference, systemLocale))
}

export function t(key: MessageKey, values: Record<string, string | number | undefined> = {}): string {
  return messages[language()][key].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`))
}
