import { createSignal } from "solid-js"

export type SupportedLanguage = "es" | "en"
export type LanguagePreference = "auto" | SupportedLanguage

export const messages = {
  es: {
    "cli.usage": "Uso: oec [OPCIONES] [PROYECTO]",
    "cli.help": "Uso: oec [OPCIONES] [PROYECTO]\n\n  -h, --help         Mostrar esta ayuda\n  -v, -V, --version  Mostrar versión\n\nConsulte man oec o docs/manual.md para la referencia completa.",
    "config.invalidJson": "El archivo no contiene JSON válido.",
    "config.invalid": "La configuración no es compatible.",
    "config.keys": "La configuración tiene claves desconocidas o faltantes.",
    "config.version": "La versión del esquema no es compatible.",
    "config.appearance": "La apariencia no es compatible.",
    "config.layout": "El layout no es válido.",
    "config.layoutRange": "El layout contiene valores fuera de rango.",
    "config.editor": "La configuración del editor no es válida.",
    "config.search": "La configuración de búsqueda no es válida.",
    "config.git": "La configuración de Git no es válida.",
    "config.updates": "La configuración de actualizaciones no es válida.",
    "config.tooLarge": "El archivo supera el límite de 256 KB.",
    "config.restored": "CONFIGURACIÓN RESTAURADA",
    "app.explorer": "Explorador",
    "app.changes": "CAMBIOS",
    "app.previous": "ANTERIOR",
    "app.new": "NUEVO",
    "app.line": "Ln",
    "app.searchFile": "Buscar archivo...",
    "app.results": "{count} resultados",
    "app.resultOne": "1 resultado",
    "app.findFile": "BUSCAR EN ARCHIVO",
    "app.typeToSearch": "Escribe para buscar...",
    "app.typeTextToSearch": "Escribe un texto para buscar.",
    "app.noMatches": "Sin coincidencias.",
    "app.findHelp": "Flechas resultado | Enter ir | Esc cerrar",
    "app.gitHelp": "+ sumar | - quitar",
    "app.commitMessage": "Mensaje de commit...",
    "app.gitSyncHelp": "F6 pull | F7 push",
    "overlay.palette": "COMANDOS Y CONFIGURACIÓN",
    "overlay.projectSearch": "BUSCAR EN TODO EL PROYECTO",
    "overlay.exclusions": "EXCLUSIONES DE BÚSQUEDA",
    "overlay.newFile": "NUEVO ARCHIVO",
    "overlay.rename": "RENOMBRAR",
    "overlay.folder": "Carpeta: {path}",
    "overlay.fileName": "nombre.ext",
    "overlay.pattern": "Carpeta o patrón...",
    "overlay.searching": "Buscando...",
    "overlay.session": "sesión",
    "overlay.project": "proyecto",
    "overlay.paletteHelp": "Flechas seleccionar | Enter ejecutar | Esc cerrar",
    "overlay.projectHelp": "Enter buscar | Ctrl+E exclusiones | Esc cerrar",
    "overlay.exclusionHelp": "Tab completar | Enter alternar | Supr quitar | Esc volver",
    "overlay.newFileHelp": "Enter crear | Esc cancelar",
    "overlay.renameHelp": "Enter renombrar | Esc cancelar",
    "overlay.confirmTitle": "Hay cambios sin guardar.",
    "overlay.confirmDescription": "Elige qué hacer con los cambios pendientes.",
    "overlay.save": "Guardar",
    "overlay.saveUpdate": "Guardar y actualizar",
    "overlay.updateWithoutSave": "Actualizar sin guardar",
    "overlay.saveQuit": "Guardar y salir",
    "overlay.quitWithoutSave": "Salir sin guardar",
    "overlay.saveClose": "Guardar y cerrar",
    "overlay.closeWithoutSave": "Cerrar sin guardar",
    "overlay.confirmHelp": "Flechas arriba/abajo | Enter confirmar | Esc cancelar",
    "overlay.delete": "Eliminar {kind}",
    "overlay.file": "archivo",
    "overlay.directory": "carpeta",
    "overlay.deleteQuestion": "¿Quieres eliminar {name}?",
    "overlay.deleteDirectory": "También se eliminará todo su contenido.",
    "overlay.irreversible": "Esta acción no se puede deshacer.",
    "overlay.actionHelp": "Enter confirmar | Esc cancelar",
    "overlay.discardGit": "Descartar cambio de Git",
    "overlay.discardGitQuestion": "¿Quieres descartar los cambios de {path}?",
    "overlay.externalChange": "El archivo cambió fuera de OEC",
    "overlay.externalChangeQuestion": "{path} fue modificado fuera de OEC. Elige cómo resolverlo.",
    "overlay.reload": "Recargar y descartar mis cambios",
    "overlay.overwrite": "Sobrescribir de todos modos",
    "overlay.cancel": "Cancelar",
    "welcome.tagline": "Editor de proyectos de código abierto para consola",
    "welcome.openPanels": "ABRIR Y MOVERSE ENTRE PANELES",
    "welcome.toggleExplorer": "MOSTRAR / OCULTAR PANEL IZQUIERDO",
    "welcome.toggleChanges": "MOSTRAR / OCULTAR CAMBIOS",
    "welcome.movePanels": "MOVERSE ENTRE PANELES",
    "welcome.files": "ARCHIVOS",
    "welcome.editing": "EDICIÓN Y BÚSQUEDA",
    "welcome.refresh": "Actualizar panel activo",
    "welcome.newFile": "Nuevo archivo",
    "welcome.delete": "Eliminar selección",
    "welcome.open": "Abrir / expandir",
    "welcome.collapseFolder": "Contraer carpeta",
    "welcome.collapseTree": "Contraer árbol",
    "welcome.palette": "Paleta de comandos",
    "welcome.findFile": "Buscar en archivo",
    "welcome.findProject": "Buscar en proyecto",
    "welcome.save": "Guardar",
    "welcome.closeTab": "Cerrar pestaña",
    "welcome.nextTab": "Siguiente pestaña",
    "welcome.clipboard": "Portapapeles",
    "welcome.undoRedo": "Deshacer / rehacer",
    "command.focusLeft": "Mover foco a la izquierda",
    "command.focusRight": "Mover foco a la derecha",
    "command.toggleExplorer": "Mostrar u ocultar explorador",
    "command.toggleGit": "Mostrar u ocultar control de cambios",
    "command.refreshGit": "Actualizar referencias remotas y cambios de Git",
    "command.refresh": "Actualizar panel activo",
    "command.create": "Crear archivo en carpeta seleccionada",
    "command.searchFile": "Buscar archivo por nombre",
    "command.searchText": "Buscar texto",
    "command.searchProject": "Buscar en todo el proyecto",
    "command.exclusions": "Editar exclusiones de búsqueda",
    "command.config": "Editar configuración de OEC",
    "command.manual": "Abrir manual de OEC",
    "command.logs": "Abrir registro de errores",
    "command.openProjectFolder": "Abrir carpeta del proyecto",
    "command.rename": "Renombrar elemento seleccionado",
    "command.save": "Guardar archivo",
    "command.close": "Cerrar archivo",
    "command.nextTab": "Pestaña siguiente",
    "command.copy": "Copiar selección",
    "command.paste": "Pegar portapapeles",
    "command.wrap": "Alternar ajuste de línea",
    "command.undo": "Deshacer último cambio",
    "command.redo": "Rehacer último cambio",
    "command.countLines": "Calcular líneas del proyecto",
    "command.palette": "Paleta",
    "command.update": "Actualización",
    "config.preview": "La configuración de preview no es válida.",
    "config.recoveryReason": "OEC no pudo iniciar con esta configuración.",
    "app.backup": "{heading}. Backup: {path}",
    "app.f4Edit": "  |  F4 editar",
    "app.f4Open": "  |  F4 abrir archivo",
    "app.noFile": "Sin archivo abierto",
    "app.diffTitle": "Cambios: {path}",
    "app.logTitle": "Registro",
    "overlay.files": "{count} archivos",
    "overlay.oneFile": "1 archivo",
    "settings.title": "CONFIGURACIÓN",
    "settings.global": "GLOBAL",
    "settings.project": "PROYECTO",
    "settings.description": "Los cambios se guardan en el JSON del ámbito activo.",
    "settings.wrap": "Ajuste de línea",
    "settings.lines": "Números de línea",
    "settings.syntax": "Resaltado de sintaxis",
    "settings.format": "Formatear al guardar",
    "settings.keyboard": "Perfil de teclado",
    "settings.help": "↑↓ seleccionar  Enter cambiar  ←→ ámbito  E editar JSON  Esc cerrar",
    "settings.word": "Palabra",
    "settings.none": "Sin ajuste",
    "settings.show": "Mostrar",
    "settings.hide": "Ocultar",
    "settings.enabled": "Activado",
    "settings.disabled": "Desactivado",
    "settings.default": "Predeterminado",
    "command.history": "Git: ver historial de commits",
    "command.branches": "Git: ver todas las ramas",
    "command.settings": "Abrir configuración",
    "command.projectConfig": "Editar configuración del proyecto",
    "command.projectFile": "Abrir archivo del proyecto",
    "command.editMarkdown": "Editar Markdown",
    "command.previewMarkdown": "Ver preview Markdown",
    "command.duplicateAbove": "Duplicar línea arriba",
    "command.duplicateBelow": "Duplicar línea abajo",
    "command.format": "Formatear documento",
    "command.massiveFiles": "Explorador: ordenar archivos masivos",
    "command.wrapSetting": "Configuración: ajuste de línea {state}",
    "command.updateVersion": "Actualizar OEC a v{version}",
    "activity.openFile": "Abriendo archivo...",
    "activity.saveFile": "Guardando archivo...",
    "activity.format": "Formateando documento...",
    "activity.createFile": "Creando archivo...",
    "activity.delete": "Eliminando elemento...",
    "activity.rename": "Renombrando elemento...",
    "activity.commit": "Creando commit...",
    "activity.pull": "Integrando cambios remotos...",
    "activity.push": "Enviando cambios al remoto...",
    "activity.reload": "Recargando archivo...",
    "activity.overwrite": "Sobrescribiendo archivo...",
    "activity.explorer": "Actualizando explorador...",
    "activity.globalConfig": "Abriendo configuración global...",
    "activity.projectConfig": "Abriendo configuración del proyecto...",
    "status.unsaved": "Hay cambios sin guardar.",
    "status.updateUnsaved": "Guarda o descarta los cambios antes de actualizar OEC.",
    "status.discarded": "Cambios descartados.",
    "status.deleteBlocked": "No se puede eliminar: hay cambios sin guardar en una pestaña afectada.",
    "status.deletedFile": "Archivo eliminado: {name}",
    "status.deletedFolder": "Carpeta eliminada: {name}",
    "status.deleteFailed": "No se pudo eliminar el elemento.",
    "status.renamed": "Renombrado: {name}",
    "status.renameFailed": "No se pudo renombrar el elemento.",
    "status.folderOpened": "Carpeta del proyecto abierta.",
    "status.folderOpenFailed": "No se pudo abrir la carpeta del proyecto.",
    "status.staged": "Cambios preparados.",
    "status.unstaged": "Cambios retirados del área preparada.",
    "status.discardBlocked": "No se pueden descartar cambios de Git: hay cambios sin guardar en una pestaña afectada.",
    "status.discardFailed": "No se pudieron descartar los cambios.",
    "status.commitMessage": "Escribe un mensaje de commit.",
    "status.nothingStaged": "No hay cambios preparados para confirmar.",
    "status.committed": "Commit creado.",
    "status.commitFailed": "No se pudo crear el commit.",
    "status.pulled": "Cambios remotos integrados.",
    "status.pullFailed": "No se pudieron integrar los cambios remotos.",
    "status.pushed": "Cambios enviados al remoto.",
    "status.pushFailed": "No se pudieron enviar los cambios al remoto.",
    "status.formatUnavailable": "El documento actual no se puede formatear.",
    "status.formatChanged": "El documento cambió durante el formateo.",
    "status.noFormatter": "No hay formateador configurado para este archivo.",
    "status.alreadyFormatted": "El documento ya tiene el formato configurado.",
    "status.formatted": "Documento formateado.",
    "status.formatFailed": "No se pudo formatear el documento.",
    "status.settingsUpdated": "Configuración actualizada.",
    "status.settingsFailed": "No se pudo actualizar la configuración.",
    "status.editorActive": "Editor activo.",
    "status.explorerActive": "Explorador activo. Flechas para seleccionar, Enter para abrir, Shift+Enter para contraer.",
    "status.gitActive": "Control de cambios activo. Flechas para seleccionar, Enter para ver el diff.",
    "status.explorerVisible": "Explorador visible.",
    "status.explorerHidden": "Explorador oculto.",
    "status.gitVisible": "Control de cambios visible.",
    "status.gitHidden": "Control de cambios oculto.",
    "log.files": "Archivos",
    "log.config": "Configuración",
    "log.explorer": "Explorador",
    "log.search": "Búsqueda",
    "log.system": "Sistema",
    "log.delete": "Eliminar elemento",
    "log.rename": "Renombrar elemento",
    "log.openFolder": "Abrir carpeta del proyecto",
    "log.openFile": "Abrir archivo",
    "log.openConfig": "Abrir configuración",
    "log.saveFile": "Guardar archivo",
    "log.createFile": "Crear archivo",
    "log.readFolder": "Leer carpeta",
    "log.projectSearch": "Buscar en proyecto",
    "log.countLines": "Calcular líneas",
    "log.fileSearch": "Buscar archivos",
    "log.unknown": "Error desconocido",
    "log.heading": "REGISTRO · SOLO LECTURA",
    "log.empty": "No hay errores registrados en esta sesión.",
    "log.oneUnread": "Falló una operación · F12 para ver detalles",
    "log.manyUnread": "{count} errores sin leer · F12 para ver detalles",
    "documents.manualOpened": "Manual de OEC abierto.",
    "documents.preview": "Preview: {path}",
    "documents.diff": "Cambios: {path}",
    "documents.logsOpened": "Registro de errores abierto.",
    "documents.opened": "Abierto: {path}",
    "documents.openFailed": "No se pudo abrir el archivo.",
    "documents.configFailed": "No se pudo abrir la configuración de OEC.",
    "documents.logTab": "REGISTRO",
    "documents.manualReadOnly": "El manual de OEC es de solo lectura.",
    "documents.imageReadOnly": "La imagen es de solo lectura.",
    "documents.logReadOnly": "El registro es de solo lectura.",
    "documents.selectFile": "Selecciona un archivo antes de guardar.",
    "documents.conflictInactive": "El archivo en conflicto ya no está activo.",
    "documents.saved": "Guardado: {name}",
    "documents.saveFailed": "No se pudo guardar el archivo.",
    "documents.saveNamedFailed": "No se pudo guardar {name}.",
    "documents.allSaved": "Todos los cambios fueron guardados.",
    "documents.reloaded": "Recargado: {name}",
    "documents.reloadFailed": "No se pudo recargar el archivo.",
    "documents.closed": "Archivo cerrado.",
    "documents.enterName": "Escribe un nombre de archivo.",
    "documents.nameFolder": "El nombre debe pertenecer a la carpeta seleccionada.",
    "documents.created": "Creado: {path}",
    "documents.createFailed": "No se pudo crear el archivo.",
    "documents.previewOnly": "El preview solo está disponible para Markdown.",
    "preview.manual": "MANUAL DE OEC · SOLO LECTURA",
    "preview.markdown": "PREVIEW MARKDOWN · F4 editar",
    "preview.image": "IMAGEN · SOLO LECTURA",
    "preview.imageFailed": "No se pudo mostrar esta imagen.",
    "files.outside": "La ruta solicitada está fuera de la carpeta abierta.",
    "files.notFile": "La ruta seleccionada no es un archivo.",
    "files.tooLarge": "El archivo supera el límite de 2 MB.",
    "files.binary": "Los archivos binarios no se pueden editar.",
    "files.invalidUtf8": "El archivo no contiene texto UTF-8 válido.",
    "files.imageTooLarge": "La imagen supera el límite de 16 MB.",
    "files.externalChange": "El archivo cambió fuera de OEC. Recarga o confirma la sobrescritura.",
    "files.exists": "Ya existe un archivo con ese nombre.",
    "files.deleteRoot": "No se puede eliminar la carpeta raíz del proyecto.",
    "files.invalidName": "El nombre no es válido.",
    "files.renameRoot": "No se puede renombrar la carpeta raíz del proyecto.",
    "files.entryExists": "Ya existe un elemento con ese nombre.",
    "explorer.readFailed": "No se pudo leer la carpeta.",
    "explorer.refreshed": "Explorador actualizado.",
    "explorer.collapsedAll": "Todas las carpetas fueron contraídas.",
    "explorer.selectFolder": "Selecciona una carpeta para contraerla.",
    "explorer.alreadyCollapsed": "La carpeta seleccionada ya está contraída.",
    "explorer.collapsed": "Carpeta contraída: {name}",
    "explorer.expanded": "Carpeta expandida: {name}",
    "explorer.invalidRoot": "La ruta inicial no es una carpeta.",
    "editor.wrapOn": "Ajuste de línea activado.",
    "editor.wrapOff": "Ajuste de línea desactivado.",
    "editor.undone": "Cambio deshecho.",
    "editor.redone": "Cambio rehecho.",
    "editor.duplicateAbove": "Línea duplicada arriba.",
    "editor.duplicateBelow": "Línea duplicada abajo.",
    "editor.selectText": "Selecciona texto antes de copiar.",
    "editor.copied": "Copiado al portapapeles.",
    "editor.copyUnsupported": "El terminal no admite la copia al portapapeles.",
    "editor.clipboardEmpty": "El portapapeles está vacío.",
    "editor.pasted": "Pegado desde el portapapeles.",
    "editor.pasteFailed": "No se pudo leer el portapapeles.",
    "editor.findPosition": "Coincidencia {index} de {count}.",
    "editor.formatExit": "El formateador {formatter} finalizó con código {code}.",
    "search.projectActivity": "Buscando en el proyecto...",
    "search.partial": " Resultado parcial: el índice alcanzó {count} entradas.",
    "search.matches": "{count} coincidencias en el proyecto.",
    "search.oneMatch": "1 coincidencia en el proyecto.",
    "search.noMatches": "No se encontraron coincidencias en el proyecto.",
    "search.failed": "No se pudo buscar en el proyecto.",
    "search.countActivity": "Calculando líneas del proyecto...",
    "search.count": "Proyecto: {lines} {lineUnit} en {files} {fileUnit} de texto.{partial}",
    "search.lineOne": "línea",
    "search.lineMany": "líneas",
    "search.fileOne": "archivo",
    "search.fileMany": "archivos",
    "search.countFailed": "No se pudieron calcular las líneas del proyecto.",
    "search.fileActivity": "Buscando archivos...",
    "search.files": "{count} archivos encontrados.",
    "search.oneFile": "1 archivo encontrado.",
    "search.noFiles": "No se encontraron archivos.",
    "search.filesFailed": "No se pudieron buscar archivos.",
    "search.exclusionsActivity": "Cargando exclusiones de búsqueda...",
    "search.massiveActivity": "Buscando archivos masivos...",
    "search.massiveResult": "{count} archivos ordenados por cantidad de líneas.{partial}",
    "search.massiveFailed": "No se pudieron ordenar los archivos por líneas.",
    "log.massive": "Ordenar archivos masivos",
    "git.refreshActivity": "Actualizando referencias remotas y cambios de Git...",
    "git.refreshed": "Referencias remotas y cambios de Git actualizados.",
    "git.partialRefresh": "Cambios de Git actualizados; no se pudieron actualizar las referencias remotas.",
    "git.checking": "Comprobando Git...",
    "git.failure": "{operation} falló{code}.",
    "git.exitCode": " (código {code})",
    "git.noDetails": "Git no devolvió detalles.",
    "git.historyFailed": "No se pudo leer el historial.",
    "git.history": "Historial: {ref}",
    "git.loadMore": "Cargar mas commits...",
    "git.branches": "Ramas locales y remotas",
    "git.remoteBranch": " [remota]",
    "git.localBranch": " [local]",
    "git.diffFailed": "No se pudo leer el diff histórico.",
    "git.changesFailed": "No se pudieron mostrar los cambios.",
    "git.loading": "Cargando...",
    "git.readOnly": "Solo lectura",
    "git.noResults": "Sin resultados",
    "git.backHelp": "Enter: abrir | Esc: volver",
    "git.historyHelp": "F8: historial | F9: ramas",
    "git.changes": "CAMBIOS",
    "git.notRepository": "Esta carpeta no es un repositorio Git.",
    "git.statusFailed": "No se pudo leer el estado de Git.",
    "git.noRemote": "sin remoto",
    "git.detached": "HEAD separado",
    "git.noChanges": "Sin cambios locales.",
    "git.synced": "actualizado",
    "git.ahead": "{ahead} adelante",
    "git.behind": "{behind} atrás",
    "git.diverged": "{ahead} adelante, {behind} atrás",
    "git.empty": "(vacío)",
    "git.startFailed": "No se pudo iniciar el proceso Git.",
    "git.invalidPath": "Ruta Git fuera del workspace o no válida.",
    "git.workspaceFailed": "No se pudo resolver la ruta del workspace en Git.",
    "git.previousPathFailed": "No se pudo determinar la ruta anterior del archivo.",
    "git.stagedFailed": "No se pudo leer la versión preparada del archivo.",
    "git.previousFailed": "No se pudo leer la versión anterior del archivo.",
    "git.outputTooLarge": "La salida de Git supera el límite permitido.",
    "git.readHistoryFailed": "No se pudo leer el historial de Git.",
    "git.binary": "Los archivos binarios no se pueden mostrar.",
    "git.invalidRevision": "Revisión no válida.",
    "git.resolveRevisionFailed": "No se pudo resolver la revisión de Git.",
    "git.invalidPage": "Página de historial no válida.",
    "git.invalidHistoricalPath": "Ruta histórica no válida.",
    "git.emptyBranch": "La rama no contiene commits.",
    "git.notHistoricalFile": "La ruta histórica no es un archivo.",
    "platform.openFolderUnsupported": "Abrir la carpeta del proyecto no está disponible en esta plataforma.",
  },
  en: {
    "cli.usage": "Usage: oec [OPTIONS] [PROJECT]",
    "cli.help": "Usage: oec [OPTIONS] [PROJECT]\n\n  -h, --help         Show this help\n  -v, -V, --version  Show version\n\nSee man oec or docs/manual.md for the full reference.",
    "config.invalidJson": "The file does not contain valid JSON.",
    "config.invalid": "The configuration is not compatible.",
    "config.keys": "The configuration has unknown or missing keys.",
    "config.version": "The schema version is not compatible.",
    "config.appearance": "The appearance configuration is not compatible.",
    "config.layout": "The layout is invalid.",
    "config.layoutRange": "The layout contains out-of-range values.",
    "config.editor": "The editor configuration is invalid.",
    "config.search": "The search configuration is invalid.",
    "config.git": "The Git configuration is invalid.",
    "config.updates": "The update configuration is invalid.",
    "config.tooLarge": "The file exceeds the 256 KB limit.",
    "config.restored": "CONFIGURATION RESTORED",
    "app.explorer": "Explorer",
    "app.changes": "CHANGES",
    "app.previous": "PREVIOUS",
    "app.new": "NEW",
    "app.line": "Ln",
    "app.searchFile": "Search files...",
    "app.results": "{count} results",
    "app.resultOne": "1 result",
    "app.findFile": "FIND IN FILE",
    "app.typeToSearch": "Type to search...",
    "app.typeTextToSearch": "Type text to search.",
    "app.noMatches": "No matches.",
    "app.findHelp": "Arrows select | Enter go | Esc close",
    "app.gitHelp": "+ add | - remove",
    "app.commitMessage": "Commit message...",
    "app.gitSyncHelp": "F6 pull | F7 push",
    "overlay.palette": "COMMANDS AND SETTINGS",
    "overlay.projectSearch": "SEARCH ENTIRE PROJECT",
    "overlay.exclusions": "SEARCH EXCLUSIONS",
    "overlay.newFile": "NEW FILE",
    "overlay.rename": "RENAME",
    "overlay.folder": "Folder: {path}",
    "overlay.fileName": "name.ext",
    "overlay.pattern": "Folder or pattern...",
    "overlay.searching": "Searching...",
    "overlay.session": "session",
    "overlay.project": "project",
    "overlay.paletteHelp": "Arrows select | Enter run | Esc close",
    "overlay.projectHelp": "Enter search | Ctrl+E exclusions | Esc close",
    "overlay.exclusionHelp": "Tab complete | Enter toggle | Del remove | Esc back",
    "overlay.newFileHelp": "Enter create | Esc cancel",
    "overlay.renameHelp": "Enter rename | Esc cancel",
    "overlay.confirmTitle": "There are unsaved changes.",
    "overlay.confirmDescription": "Choose what to do with pending changes.",
    "overlay.save": "Save",
    "overlay.saveUpdate": "Save and update",
    "overlay.updateWithoutSave": "Update without saving",
    "overlay.saveQuit": "Save and quit",
    "overlay.quitWithoutSave": "Quit without saving",
    "overlay.saveClose": "Save and close",
    "overlay.closeWithoutSave": "Close without saving",
    "overlay.confirmHelp": "Up/down arrows | Enter confirm | Esc cancel",
    "overlay.delete": "Delete {kind}",
    "overlay.file": "file",
    "overlay.directory": "folder",
    "overlay.deleteQuestion": "Do you want to delete {name}?",
    "overlay.deleteDirectory": "All of its contents will also be deleted.",
    "overlay.irreversible": "This action cannot be undone.",
    "overlay.actionHelp": "Enter confirm | Esc cancel",
    "overlay.discardGit": "Discard Git change",
    "overlay.discardGitQuestion": "Do you want to discard changes in {path}?",
    "overlay.externalChange": "The file changed outside OEC",
    "overlay.externalChangeQuestion": "{path} was modified outside OEC. Choose how to resolve it.",
    "overlay.reload": "Reload and discard my changes",
    "overlay.overwrite": "Overwrite anyway",
    "overlay.cancel": "Cancel",
    "welcome.tagline": "An open-source project editor for the terminal",
    "welcome.openPanels": "OPEN AND MOVE BETWEEN PANELS",
    "welcome.toggleExplorer": "SHOW / HIDE LEFT PANEL",
    "welcome.toggleChanges": "SHOW / HIDE CHANGES",
    "welcome.movePanels": "MOVE BETWEEN PANELS",
    "welcome.files": "FILES",
    "welcome.editing": "EDITING AND SEARCH",
    "welcome.refresh": "Refresh active panel",
    "welcome.newFile": "New file",
    "welcome.delete": "Delete selection",
    "welcome.open": "Open / expand",
    "welcome.collapseFolder": "Collapse folder",
    "welcome.collapseTree": "Collapse tree",
    "welcome.palette": "Command palette",
    "welcome.findFile": "Find in file",
    "welcome.findProject": "Find in project",
    "welcome.save": "Save",
    "welcome.closeTab": "Close tab",
    "welcome.nextTab": "Next tab",
    "welcome.clipboard": "Clipboard",
    "welcome.undoRedo": "Undo / redo",
    "command.focusLeft": "Move focus left",
    "command.focusRight": "Move focus right",
    "command.toggleExplorer": "Show or hide explorer",
    "command.toggleGit": "Show or hide source control",
    "command.refreshGit": "Refresh Git remote references and changes",
    "command.refresh": "Refresh active panel",
    "command.create": "Create file in selected folder",
    "command.searchFile": "Search files by name",
    "command.searchText": "Search text",
    "command.searchProject": "Search entire project",
    "command.exclusions": "Edit search exclusions",
    "command.config": "Edit OEC configuration",
    "command.manual": "Open OEC manual",
    "command.logs": "Open error log",
    "command.openProjectFolder": "Open project folder",
    "command.rename": "Rename selected item",
    "command.save": "Save file",
    "command.close": "Close file",
    "command.nextTab": "Next tab",
    "command.copy": "Copy selection",
    "command.paste": "Paste clipboard",
    "command.wrap": "Toggle line wrap",
    "command.undo": "Undo last change",
    "command.redo": "Redo last change",
    "command.countLines": "Count project lines",
    "command.palette": "Palette",
    "command.update": "Update",
    "config.preview": "The preview configuration is invalid.",
    "config.recoveryReason": "OEC could not start with this configuration.",
    "app.backup": "{heading}. Backup: {path}",
    "app.f4Edit": "  |  F4 edit",
    "app.f4Open": "  |  F4 open file",
    "app.noFile": "No file open",
    "app.diffTitle": "Changes: {path}",
    "app.logTitle": "Log",
    "overlay.files": "{count} files",
    "overlay.oneFile": "1 file",
    "settings.title": "SETTINGS",
    "settings.global": "GLOBAL",
    "settings.project": "PROJECT",
    "settings.description": "Changes are saved to the JSON for the active scope.",
    "settings.wrap": "Line wrap",
    "settings.lines": "Line numbers",
    "settings.syntax": "Syntax highlighting",
    "settings.format": "Format on save",
    "settings.keyboard": "Keyboard profile",
    "settings.help": "↑↓ select  Enter change  ←→ scope  E edit JSON  Esc close",
    "settings.word": "Word",
    "settings.none": "No wrap",
    "settings.show": "Show",
    "settings.hide": "Hide",
    "settings.enabled": "Enabled",
    "settings.disabled": "Disabled",
    "settings.default": "Default",
    "command.history": "Git: view commit history",
    "command.branches": "Git: view all branches",
    "command.settings": "Open settings",
    "command.projectConfig": "Edit project configuration",
    "command.projectFile": "Open project file",
    "command.editMarkdown": "Edit Markdown",
    "command.previewMarkdown": "Show Markdown preview",
    "command.duplicateAbove": "Duplicate line above",
    "command.duplicateBelow": "Duplicate line below",
    "command.format": "Format document",
    "command.massiveFiles": "Explorer: sort massive files",
    "command.wrapSetting": "Settings: line wrap {state}",
    "command.updateVersion": "Update OEC to v{version}",
    "activity.openFile": "Opening file...",
    "activity.saveFile": "Saving file...",
    "activity.format": "Formatting document...",
    "activity.createFile": "Creating file...",
    "activity.delete": "Deleting item...",
    "activity.rename": "Renaming item...",
    "activity.commit": "Creating commit...",
    "activity.pull": "Pulling remote changes...",
    "activity.push": "Pushing changes to remote...",
    "activity.reload": "Reloading file...",
    "activity.overwrite": "Overwriting file...",
    "activity.explorer": "Refreshing explorer...",
    "activity.globalConfig": "Opening global configuration...",
    "activity.projectConfig": "Opening project configuration...",
    "status.unsaved": "There are unsaved changes.",
    "status.updateUnsaved": "Save or discard changes before updating OEC.",
    "status.discarded": "Changes discarded.",
    "status.deleteBlocked": "Cannot delete: an affected tab has unsaved changes.",
    "status.deletedFile": "File deleted: {name}",
    "status.deletedFolder": "Folder deleted: {name}",
    "status.deleteFailed": "Could not delete the item.",
    "status.renamed": "Renamed: {name}",
    "status.renameFailed": "Could not rename the item.",
    "status.folderOpened": "Project folder opened.",
    "status.folderOpenFailed": "Could not open the project folder.",
    "status.staged": "Changes staged.",
    "status.unstaged": "Changes unstaged.",
    "status.discardBlocked": "Cannot discard Git changes: an affected tab has unsaved changes.",
    "status.discardFailed": "Could not discard changes.",
    "status.commitMessage": "Enter a commit message.",
    "status.nothingStaged": "There are no staged changes to commit.",
    "status.committed": "Commit created.",
    "status.commitFailed": "Could not create the commit.",
    "status.pulled": "Remote changes integrated.",
    "status.pullFailed": "Could not integrate remote changes.",
    "status.pushed": "Changes pushed to remote.",
    "status.pushFailed": "Could not push changes to remote.",
    "status.formatUnavailable": "The current document cannot be formatted.",
    "status.formatChanged": "The document changed during formatting.",
    "status.noFormatter": "No formatter is configured for this file.",
    "status.alreadyFormatted": "The document is already formatted.",
    "status.formatted": "Document formatted.",
    "status.formatFailed": "Could not format the document.",
    "status.settingsUpdated": "Settings updated.",
    "status.settingsFailed": "Could not update settings.",
    "status.editorActive": "Editor active.",
    "status.explorerActive": "Explorer active. Use arrows to select, Enter to open, Shift+Enter to collapse.",
    "status.gitActive": "Source control active. Use arrows to select, Enter to view the diff.",
    "status.explorerVisible": "Explorer visible.",
    "status.explorerHidden": "Explorer hidden.",
    "status.gitVisible": "Source control visible.",
    "status.gitHidden": "Source control hidden.",
    "log.files": "Files",
    "log.config": "Configuration",
    "log.explorer": "Explorer",
    "log.search": "Search",
    "log.system": "System",
    "log.delete": "Delete item",
    "log.rename": "Rename item",
    "log.openFolder": "Open project folder",
    "log.openFile": "Open file",
    "log.openConfig": "Open configuration",
    "log.saveFile": "Save file",
    "log.createFile": "Create file",
    "log.readFolder": "Read folder",
    "log.projectSearch": "Search project",
    "log.countLines": "Count lines",
    "log.fileSearch": "Search files",
    "log.unknown": "Unknown error",
    "log.heading": "LOG · READ ONLY",
    "log.empty": "No errors recorded in this session.",
    "log.oneUnread": "An operation failed · F12 for details",
    "log.manyUnread": "{count} unread errors · F12 for details",
    "documents.manualOpened": "OEC manual opened.",
    "documents.preview": "Preview: {path}",
    "documents.diff": "Changes: {path}",
    "documents.logsOpened": "Error log opened.",
    "documents.opened": "Opened: {path}",
    "documents.openFailed": "Could not open the file.",
    "documents.configFailed": "Could not open the OEC configuration.",
    "documents.logTab": "LOG",
    "documents.manualReadOnly": "The OEC manual is read-only.",
    "documents.imageReadOnly": "The image is read-only.",
    "documents.logReadOnly": "The log is read-only.",
    "documents.selectFile": "Select a file before saving.",
    "documents.conflictInactive": "The conflicting file is no longer active.",
    "documents.saved": "Saved: {name}",
    "documents.saveFailed": "Could not save the file.",
    "documents.saveNamedFailed": "Could not save {name}.",
    "documents.allSaved": "All changes saved.",
    "documents.reloaded": "Reloaded: {name}",
    "documents.reloadFailed": "Could not reload the file.",
    "documents.closed": "File closed.",
    "documents.enterName": "Enter a file name.",
    "documents.nameFolder": "The name must belong to the selected folder.",
    "documents.created": "Created: {path}",
    "documents.createFailed": "Could not create the file.",
    "documents.previewOnly": "Preview is only available for Markdown.",
    "preview.manual": "OEC MANUAL · READ ONLY",
    "preview.markdown": "MARKDOWN PREVIEW · F4 edit",
    "preview.image": "IMAGE · READ ONLY",
    "preview.imageFailed": "Could not display this image.",
    "files.outside": "The requested path is outside the open folder.",
    "files.notFile": "The selected path is not a file.",
    "files.tooLarge": "The file exceeds the 2 MB limit.",
    "files.binary": "Binary files cannot be edited.",
    "files.invalidUtf8": "The file does not contain valid UTF-8 text.",
    "files.imageTooLarge": "The image exceeds the 16 MB limit.",
    "files.externalChange": "The file changed outside OEC. Reload or confirm overwriting it.",
    "files.exists": "A file with that name already exists.",
    "files.deleteRoot": "The project root folder cannot be deleted.",
    "files.invalidName": "The name is invalid.",
    "files.renameRoot": "The project root folder cannot be renamed.",
    "files.entryExists": "An item with that name already exists.",
    "explorer.readFailed": "Could not read the folder.",
    "explorer.refreshed": "Explorer refreshed.",
    "explorer.collapsedAll": "All folders collapsed.",
    "explorer.selectFolder": "Select a folder to collapse.",
    "explorer.alreadyCollapsed": "The selected folder is already collapsed.",
    "explorer.collapsed": "Folder collapsed: {name}",
    "explorer.expanded": "Folder expanded: {name}",
    "explorer.invalidRoot": "The initial path is not a folder.",
    "editor.wrapOn": "Line wrap enabled.",
    "editor.wrapOff": "Line wrap disabled.",
    "editor.undone": "Change undone.",
    "editor.redone": "Change redone.",
    "editor.duplicateAbove": "Line duplicated above.",
    "editor.duplicateBelow": "Line duplicated below.",
    "editor.selectText": "Select text before copying.",
    "editor.copied": "Copied to clipboard.",
    "editor.copyUnsupported": "This terminal does not support clipboard copying.",
    "editor.clipboardEmpty": "The clipboard is empty.",
    "editor.pasted": "Pasted from clipboard.",
    "editor.pasteFailed": "Could not read the clipboard.",
    "editor.findPosition": "Match {index} of {count}.",
    "editor.formatExit": "Formatter {formatter} exited with code {code}.",
    "search.projectActivity": "Searching project...",
    "search.partial": " Partial results: the index reached {count} entries.",
    "search.matches": "{count} matches in project.",
    "search.oneMatch": "1 match in project.",
    "search.noMatches": "No matches found in project.",
    "search.failed": "Could not search the project.",
    "search.countActivity": "Counting project lines...",
    "search.count": "Project: {lines} {lineUnit} in {files} text {fileUnit}.{partial}",
    "search.lineOne": "line",
    "search.lineMany": "lines",
    "search.fileOne": "file",
    "search.fileMany": "files",
    "search.countFailed": "Could not count project lines.",
    "search.fileActivity": "Searching files...",
    "search.files": "{count} files found.",
    "search.oneFile": "1 file found.",
    "search.noFiles": "No files found.",
    "search.filesFailed": "Could not search files.",
    "search.exclusionsActivity": "Loading search exclusions...",
    "search.massiveActivity": "Finding massive files...",
    "search.massiveResult": "{count} files sorted by line count.{partial}",
    "search.massiveFailed": "Could not sort files by line count.",
    "log.massive": "Sort massive files",
    "git.refreshActivity": "Refreshing remote references and Git changes...",
    "git.refreshed": "Remote references and Git changes refreshed.",
    "git.partialRefresh": "Git changes refreshed; remote references could not be refreshed.",
    "git.checking": "Checking Git...",
    "git.failure": "{operation} failed{code}.",
    "git.exitCode": " (exit code {code})",
    "git.noDetails": "Git provided no details.",
    "git.historyFailed": "Could not read history.",
    "git.history": "History: {ref}",
    "git.loadMore": "Load more commits...",
    "git.branches": "Local and remote branches",
    "git.remoteBranch": " [remote]",
    "git.localBranch": " [local]",
    "git.diffFailed": "Could not read historical diff.",
    "git.changesFailed": "Could not show changes.",
    "git.loading": "Loading...",
    "git.readOnly": "Read only",
    "git.noResults": "No results",
    "git.backHelp": "Enter: open | Esc: back",
    "git.historyHelp": "F8: history | F9: branches",
    "git.changes": "CHANGES",
    "git.notRepository": "This folder is not a Git repository.",
    "git.statusFailed": "Could not read Git status.",
    "git.noRemote": "no remote",
    "git.detached": "detached HEAD",
    "git.noChanges": "No local changes.",
    "git.synced": "up to date",
    "git.ahead": "{ahead} ahead",
    "git.behind": "{behind} behind",
    "git.diverged": "{ahead} ahead, {behind} behind",
    "git.empty": "(empty)",
    "git.startFailed": "Could not start the Git process.",
    "git.invalidPath": "Git path outside the workspace or invalid.",
    "git.workspaceFailed": "Could not resolve the workspace path in Git.",
    "git.previousPathFailed": "Could not determine the file's previous path.",
    "git.stagedFailed": "Could not read the staged version of the file.",
    "git.previousFailed": "Could not read the previous version of the file.",
    "git.outputTooLarge": "Git output exceeds the allowed limit.",
    "git.readHistoryFailed": "Could not read Git history.",
    "git.binary": "Binary files cannot be displayed.",
    "git.invalidRevision": "Invalid revision.",
    "git.resolveRevisionFailed": "Could not resolve the Git revision.",
    "git.invalidPage": "Invalid history page.",
    "git.invalidHistoricalPath": "Invalid historical path.",
    "git.emptyBranch": "The branch contains no commits.",
    "git.notHistoricalFile": "The historical path is not a file.",
    "platform.openFolderUnsupported": "Opening the project folder is not available on this platform.",
  },
} as const

export type MessageKey = keyof typeof messages.es
const catalogs: Record<SupportedLanguage, Record<MessageKey, string>> = messages

export function detectSystemLanguage(locale = Intl.DateTimeFormat().resolvedOptions().locale): SupportedLanguage {
  return locale.toLowerCase().startsWith("es") ? "es" : "en"
}

export function resolveLanguage(preference: LanguagePreference | undefined, systemLocale?: string): SupportedLanguage {
  return preference === "es" || preference === "en" ? preference : detectSystemLanguage(systemLocale)
}

const [language, setLanguage] = createSignal<SupportedLanguage>(detectSystemLanguage())

export { language }

export function configureLanguage(preference: LanguagePreference | undefined, systemLocale?: string) {
  setLanguage(resolveLanguage(preference, systemLocale))
}

export function t(key: MessageKey, values: Record<string, string | number | undefined> = {}): string {
  return catalogs[language()][key].replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`))
}

export function formatNumber(value: number): string { return new Intl.NumberFormat(language()).format(value) }

const knownMessages = new Map<string, MessageKey>()
const dynamicMessages: Array<{ key: MessageKey; prefix: string; names: string[]; pattern: RegExp }> = []
for (const source of Object.values(messages)) {
  for (const [rawKey, template] of Object.entries(source)) {
    const key = rawKey as MessageKey
    if (!template.includes("{")) { knownMessages.set(template, key); continue }
    const parts = template.split(/\{\w+\}/)
    if (!parts[0] || parts[0].length < 3) continue
    dynamicMessages.push({
      key, prefix: parts[0],
      names: [...template.matchAll(/\{(\w+)\}/g)].map((match) => match[1]!),
      pattern: new RegExp(`^${parts.map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("([\\s\\S]*?)")}$`),
    })
  }
}

export function translateKnown(message: string): string {
  const key = knownMessages.get(message)
  if (key) return t(key)
  for (const dynamic of dynamicMessages) {
    if (!message.startsWith(dynamic.prefix)) continue
    const match = dynamic.pattern.exec(message)
    if (match) return t(dynamic.key, Object.fromEntries(dynamic.names.map((name, index) => {
      const value = match[index + 1] ?? ""
      if (name === "partial" || name === "lineUnit" || name === "fileUnit" || name === "heading" || name === "state") return [name, translateKnown(value)]
      if (["count", "lines", "files", "index"].includes(name) && /^\d[\d.,]*$/.test(value)) return [name, formatNumber(Number(value.replace(/[.,]/g, "")))]
      return [name, value]
    })))
  }
  return message
}
